### ISSUE TITLE
Inkonsekvens mellan beskrivning och köplänk för kopplingskablar

### ISSUE THREAD

**Issue by GoranGozo** [luftdata/luftdata.se#8]
I inköpslista med delar som behövs finns en punkt:
"Kopplingskablar, ca. 20 cm, hona-hona [Kjell]"

I beskrivningen står det att kablarna ska vara hona-hona.
Länken till Kjell leder till kablar som är hane-hane.

**Comment by ebner** [comment]
Fixat, tack!
